Dev
KaurkerDevourer/ff4 pull request #1
Opened 2024-01-31 12:07 UTC by KaurkerDevourer

Первая пр, чтобы занести всю математику и остальное вокруг F4, вероятно тут же будет алгоритм Бухбергера.

2024-02-16 19:45 UTC, KaurkerDevourer commented
@DimaTrushin можно смотреть

2024-02-18 20:44 UTC, KaurkerDevourer commented on tests/testing.h
> +#define ASSERT_EQUAL(A, B) \
заменить на libassert

2024-02-19 10:52 UTC, DimaTrushin requested changes
Обрати внимание, что я не повторял замечания. Если одна и та же ошибка всречалась несколько раз, я комментировал лишь единожды. Потому я ожидаю, что ты поправишь все аналогичные замечания всюду.

На мой взгляд идеальный проект человека, который ничему не хотел научиться и не читал ни манула, ни смотрел записи курса по плюсам.

2024-02-19 10:52 UTC, DimaTrushin commented on .gitignore
> +*.gch*
Добавь пустую строку в конце каждого файла. Дело в том, что гит на это ругается и пользователь твоего репозитория будет видеть сообщения об ошибках от гита. Не делай так.
Добавить в clang-format правило:
InsertNewlineAtEOF: true

2024-02-19 10:52 UTC, DimaTrushin commented on README.md
Добавь систему сборки, например cmake. А то у тебя все make файлы написаны руками и фиг его знает как это собираеть. Если хоть что-то из настроек не такое, как у тебя.

2024-02-19 10:52 UTC, DimaTrushin commented on README.md
> +g++ main.cpp -o ../bin/test -O3 -mavx512f -mavx512cd -mavx512er -mavx512pf -mavx512dq -mavx512vl -mavx512ifma -mavx512vbmi -mavx512bw
У тебя машина avx512 поддерживает?

2024-02-19 10:52 UTC, DimaTrushin commented on benchmarks/buchberger/Makefile
> +FLAGS=-std=c++20 -O3 -march=native
У тебя ни на чем кроме как на gcc это не соберется. Это не очень гуд.

2024-02-19 10:52 UTC, DimaTrushin commented on benchmarks/buchberger/Makefile
> +	$(CC) $(FLAGS) main.cpp ../../lib/algo/buchberger.h ../../lib/algo/buchberger.cpp ../../lib/util/math.h ../../lib/util/math.cpp ../../lib/util/monomial.h ../../lib/util/monomial.cpp ../../lib/util/p
Зачем тебе h файлы?

2024-02-19 10:52 UTC, DimaTrushin commented on benchmarks/sum/Makefile
> +sum: main.cpp ../benchmarking.h
Зачем h файлы в единицах трансляции? Это ошибка. Компилируются только cpp файлы, а h файлы инклудятся диррективами в cpp файлы.

2024-02-19 10:52 UTC, DimaTrushin commented on tests/rational/main.cpp
> +int main() {
У тебя не отключены exception, потому надо поставить блок на них. Это делается так
```cpp
#include "Test.h"
#include "Except.h"

int main() {
  try {
    Test::run_all_tests();
  } catch(...) {
    except::react();
  }
  return 0;
}
Except.h
namespace except {
void react();
}
Except.cpp
#include "Except.h"

namespace except {
void react() {
  try {
    throw;
  } catch(std::exception& e) {
    // обрабатываешь известные исключения
  } catch(...) {
    // обрабатываешь незивестные исключения
  }
}
}
```

2024-02-19 10:52 UTC, DimaTrushin commented on tests/testing.h
> +  char** strs = backtrace_symbols(callstack, frames);
Эта функция из ядра линукса. Это плохое решение.
1) Во-первых, этот код не запустится нигде кроме линукса. Это очень плохо особенно для библиотеки, которая никак к операционной системе не привязана. Если тебе нужно использовать специфические функции для специфических операционных систем, то правильно делать не так. Делаешь testing.h и объявляешь функцию с независимым от OS API. Делаешь для каждой операционной системы свою имплементацию в файлах testing_win.cpp, testing_lin.cpp, testing_mac.cpp. И в системе сборки в зависимости от target OS подключаешь только один из трех файлов cpp. Тогда независимо от перационной системы у тебя проект соберется и будет нужная функция. Если что можно на неизвестных тебе операционных системах сделать пустые заглушки, но главное, проект соберется.
2) C++ сформулирован в терминах абстрактной машины. У него абстрактные правила корректности. А состояние стека -- это конкретное исполнение. Потому это идейно не верно проверять состояние стека.
3) Идейно ты тут пытаешься кустарно симулировать дебагер. Куда лучше просто воспользоваться дебагером. Он делает всю ту же работу лучше, чем сделаешь ты, просто из объективных причин.
4) Дебагер -- это последняя линия обороны. Лучше не доводить до дебагера и делать проверки через assert-ы.

2024-02-19 10:52 UTC, DimaTrushin commented on tests/testing.h
> +  free(strs);
- Даже если ты пишешь сишный код, который не бросает, то я рекомендую использовать raii, чтобы не забывать автоматически чистить ресурсы.
- Кроме того, у тебя может быть ситуация, когда ты инициализируешь много взаимозависимых ресурсов в разных порядках и проследить все возможные ситуации, как их  надо чистить руками бывает сложно. В этом случае всегда поможет raii.
- Кроме того, ты ломаешь стиль написания кода. Если ты хочешь использовать чисто сишные функции. То выдели их в отдельную библиотеку, компилируй ее с помощью Си компилятора и потом линкуй через extern "C". Но не используй эти функции напрямую в проекте, оборачивай их в c++ обертки. Так ты сможешь разделить код и не перемешивать стили.

2024-02-19 10:52 UTC, DimaTrushin commented on tests/testing.h
> +        backtrace(); \
Я так и не понял, зачем тебе тут эта функция. Если ты хочешь сообщить об ошибке, тебе должно быть достаточно данных передаваемых в качестве аргументов.

2024-02-19 10:52 UTC, DimaTrushin commented on tests/testing.h
> +void backtrace() {
У тебя ODR violation. Ты в h файле имплементируешь функцию без inline модификатора. Это чистым видом UB.

2024-02-19 10:52 UTC, DimaTrushin commented on tests/testing.h
> +  void* callstack[128];
Даже если ты пользуешься сишным кодом в C++ проекте, не используй Сишные массивы. Используй std::array.

2024-02-19 10:52 UTC, DimaTrushin commented on tests/testing.h
> +    std::cout << strs[i] << std::endl;
std::cout может кинуть исключение. Когда ты мешаешь Сишный код и плюсовый код, можно незаметить подобных вещей и получить утечку ресурсов. Если память операционка умеет чистить после завершения твоей программы, то есть куча других ресурсов, которые она может не суметь почистить. Либо делай отдельно сишную библиотеку и компилируй ее сишным компилятором, либо пиши полностью в стиле плюсов.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/rational.h
> +    private:
Нет смысла повторять квалификатор доступа.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/rational.cpp
> +        if (denominator_ < 0) {
- Заведи функцию normalize, которая делает всю работу
1) делает знаменатель положительным
2) делает дробь неприводимой.
 и зови тут эту функцию.
- У тебя нарушение уровня абстракции. В начале низкоуровневая работа руками напрямую с полями класса, а потом ты вызываешь функцию, которая все делает внутри себя. Как минимум первое тогда надо тоже оборачивать в функцию.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/rational.cpp
> +        return left.numerator_ * right.denominator_ > right.numerator_ * left.denominator_;
Не пиши имплементацию для зависимых операторов, пиши их через имплементацию первого оператора, например тут можно написать
```cpp
return right < left;
```

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/rational.cpp
> +        return (left.numerator_ != right.numerator_) || (left.numerator_ != 0 && (left.denominator_ != right.denominator_));
```cpp
return !(left == right);
```

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/rational.cpp
> +        return Rational(-GetNumerator(), GetDenominator());
В методах класса можно напрямую обращаться к полям и не использвать функции аксессоры. Это нужно для единообразия.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/rational.cpp
> +        numerator_ = GetNumerator() * other.GetDenominator() + other.GetNumerator() * GetDenominator();
Неконсистентность. Ты в методах выше везде обращался напрямую к имплементации через numerator_ и denomenator_, а тут внезапно начал использовать функции аксессоры. Надо все делать в едином стиле.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/rational.cpp
> +        numerator_ *= other.GetDenominator();
Поставь assert, что other != 0

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/math.h
> +    int64_t gcd(int64_t a, int64_t b) __attribute__((const));
- А чем тебя не устроил std::gcd?
- В чем смысл аттрибута в конце?

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/math.cpp
> +        int64_t az = __builtin_ctz(a);
Ты опять используешь builtin функции компилятора. Этот код не соберется на любом другом компиляторе кроме как на gcc. Плохой стиль. Нужно делать тогда разные cpp файлы с разными имплементациями под разные компиляторы и в системе сборке настраивать переключение. Не делай так никогда.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/math.cpp
> +
Вот тут для удобства можно воткнуть
```cpp
assert(a > 0);
assert(b > 0);
```
Чтобы и программист и компилятор понимали, что с этого места мы работаем только с положительными числами и у нас нет всяких UB из-за сдвигов знаковых типов. Это в основном нужно для программиста, чтобы не проверять глазами, что тут действительно все положительное. Конкретно в этой функции это и так видно (хоть и требует на 1 секунду больше времени, чем увидеть assert), но стоит взять это за привычку.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/rational.cpp
> +    // private
убери комментарий.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/monomial.h
> +    using TTerm = std::vector<int64_t>;
Такое определение терма означает, что ты не поддерживаешь никакие инварианты. У тебя вектор может быть любых размеров и содержать любые значения. Что-то мне подсказывает, что это ошибка. Потому что ты хочешь все же иметь положительные степени у переменных. Кроме того, ты вряд ли хочешь хранить кучу нулей в конце вектора. Судя по всему стоит это выделить в отдельный класс.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/monomial.h
> +        Monomial() = default;
поставь этот конструктор первым и убери между конструкторами пробел.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/monomial.h
> +        Monomial(TTerm term, Rational coef = (int64_t)1);
У тебя int64_t испльзуется в двух смыслах:
1) Степень в терме
2) Число в рациональной дроби.

Надо разделить эти два имени хотя бы юзингами.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/monomial.h
> +        Monomial(TTerm term, Rational coef = (int64_t)1);
У тебя мономы не поддерживают никаких коэффициентов кроме рациональных чисел. Много тестов заточено на поля вычетов по модулю простого. Надо добавить их поддержку.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/monomial.cpp
> +    Monomial::Monomial(std::vector<int64_t> term, Rational coef)
- Очень плохо. Ты используешь прямое имя вместо using-га, который ты завел. При изменении Term-а на другую имплементацию у тебя возможны две ситуации:
1) Это не скомпилируется (это еще хороший исход)
2) Это скомпилируется, но у тебя все время будет две лишнии конвертации типов. Одна во время присвоения аргументу, вторая во время передачи аргумента в term_ в списке инициализации. В итоге это редукция производительности.

- В целом я не люблю делать конструкторы от конкретных контейнеров, потому что пользователь может написать так
```cpp
Monomial m({1, 2, 3}, 1);
```
В этом случае {1, 2, 3} является std::initializer_list<int>. Он создастся на стеке. После этого у тебя по нему сконструируется его копия в виде std::vector<int64_t> в аргументе конструктора. И потом ниже, ты эту копию еще раз скопируешь в списке инициализации во время term_(term). Это очень плохой подход.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/monomial.cpp
> +    : term_(term)
Если конструктор принимает аргумент by value, то не надо его копировать, делай
```cpp
 : term_(std::move(term))
```
Чтобы хотя бы украсть кишки у этого объекта.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/monomial.cpp
> +        Normalize(term_);
- Это ошибка дизайна. Это инвариант терма, а не монома. Он сам должен редуцировать сам себя.
- Кроме того, у тебя у тебя явно term_ принимается как ссылка, потому что иначе он просто не может измениться. Это плохой дизайн. Синтаксис никак не говорит об этом.
- У тебя еще может быть нулевой коэффициент и в этом случае тебе надо терм заменить на 1. И ты либо пролюбил этот случай, либо ты это неявно делаешь в методе Normalize, что еще хуже, потому что это скрытая зависимость и не консистентность (терм передается явно, а коэффициент нет).

Переписать по нормальному.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/monomial.cpp
> +        while(term.size() && term.back() == 0) {
- Как я и думал, ты провафлил случай  нулевого коэффициента.
- Лучше сделать функцию Normalize которая возвращает новый терм, например
```cpp
Term normalize(Term&& term)
```
И тогда можно редуцировать налету
```cpp
Monomial(...)
 : temr_(normalize(term)) {}
```
Но лучше не заниматься ерундой и отдать эту задачу тому, кто ей должен заниматься, а именно конструктор класса Term.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/monomial.h
> +        void AddCoef(const Monomial& other) noexcept;
Почему не set? И в целом как-то криво выглядит.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/monomial.h
> +        bool IsDivisibleBy(const Monomial&) const noexcept __attribute__((pure));
- Это опять компиляторо зависимый атрибут. Плохой стиль.
- Почему не __attribute__((const))? У тебя что эта функция читает глобальную память?

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/monomial.h
> +        friend Monomial lcm(const Monomial&, const Monomial&) noexcept;
Эти операции не корректны для монома. Они корректны только для терма. Более чем уверен, что у тебя не выполняется инвариант m * n = gcd(m, n) * lcm(m, n).

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/monomial.h
> +        static void Normalize(TTerm&);
какого хуя эта функция публичная!?

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/monomial.h
> +    using TMonomials = std::vector<Monomial>;
Не делай такой глобальный using. Ты это используешь только в имплементации Polynomial. Вот и запихни это туда в детали имплементации многочлена. Мало ли как ты можешь поменять потом эту имплементацию. Ты просто ломаешь локальность зависимости вынося кишки полинома сюда.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/monomial.cpp
> +            return false;
Вот тут не корректное сравнение. Если коэффициенты нулевые, то у тебя любые два монома равны. А у тебя не поддерживается инвариант, что при нулевом коэффициенте термы равны 1. Потому тут у тебя будет неверный результат сравнения, если коэффициенты нулевые, а термы не совпадают.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/monomial.cpp
> +        for (size_t i = 0; i < std::min(left.term_.size(), right.term_.size()); i++) {
Лишний вызов std::min. У тебя в этой точке выполняется инвариант, что размеры одинаковые.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/monomial.cpp
> +        if (left.term_.size() != right.term_.size()) {
Начиная с этой строчки код -- мусор. Его можно заменить одной строчкой
```cpp
return left.term_ == right.term_;
```
Но все равно это будет не верная имплементация при нулевом коэффициенте.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/monomial.cpp
> +        if (left.term_.size() != right.term_.size()) {
Всегда когда видишь код вида left.term_.size(), где у тебя более одной точки подряд, это ошибка дизайна! Ты стучишься в кишки кишков своего объекта. Это означает, что ты что-то делаешь не так. Ты не обеспечил объекты нужными интерфейсами для взаимодействия с ними и вместо этого взаимодействуешь с их внуренностями напрямую. Но в этом случае тебе повезло, ты просто не позвал нужный оператор сравнения векторов.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/monomial.cpp
> +        if (left.coef_ != right.coef_) {
Дупликация кода
```cpp
return !(left == right);
```
И не надо будет переписывать неверную имплементацию.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/monomial.h
> +        friend bool operator<(const Monomial&, const Monomial&) noexcept;
1) Наличие такого оператор означает, что ты зафиксировал некоторый порядок на мономах, который никак нельзя менять. Это плохо. Я хочу иметь возможность поддерживать разные порядки. Можно иметь такой оператор в мономах, но тогда он должен быть шаблонным параметром. То есть у тебя моном с порядком, а не просто моном.
2) Сравнение для мономов не совсем корректное. Оно будет корректно лишь для термов. А что ты будешь делать с коэффициентами? Ты вводишь частичный порядок и объявляешь их не сравнимыми? Ты делаешь предпорядок и объявляешь их эквивалентными? Ты точно учитываешь нулевой коэффициент правильно?

В общем, ты как в той песне "я его слепила из того что было, а потом что было, то и полюбила". Ты слепил вместе две сущности и не правильно установил границы интерфейсов. У тебя потому получается какая-то дичь со все более сложными костылями.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/rational.cpp
> +        return left.numerator_ * right.denominator_ < right.numerator_ * left.denominator_;
Добавсь всем методам проверку на overflow! При работе с базисами гребнера это может в легкую случиться.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/monomial.cpp
> +    bool Monomial::IsDivisibleBy(const Monomial& other) const noexcept {
Так как у тебя степени в терме любого знака, то делимость не имеет смысла. Ты не поддерживаешь никакой инвариант. Это плохо.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/monomial.cpp
> +    bool operator<(const Monomial& left, const Monomial& right) noexcept {
std::lexicographical_compare

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/monomial.cpp
> +        Normalize(term_);
А зачем тут делать нормализацию? Она вроде как никогда не нужна (если только у тебя есть отрицательные степени, что противоречит смыслу мономов).

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/monomial.cpp
> +        coef_ /= other.GetCoef();
ассерт на other, что он не ноль.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/monomial.cpp
> +        return Monomial(std::move(term), 1);
Как я и думал, у тебя не выполняется инвариант на gcd и lcm.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/monomial.cpp
> +        Monomial::Normalize(term);
Тут не должна быть нужна нормализация.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/monomial.cpp
> +        }
Стоит добавить метод
```cpp
Degree degree(Index index) const;
```
Который возвращает степень переменной по индексу для любого индекса, даже того, который не входит в контейнер (тогда возвращается 0). Это может работать медленнее, но это может быть удобно для пользователя снаружи.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/polynomial.h
> +        const Monomial& GetHeadMonomial() const noexcept;
Плохо. Ты открываешь кишки имплементации. Такого быть не должно.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/polynomial.h
> +        explicit Polynomial(TMonomials&& monomials);
1) А почему у мономов ты не принимал по rvalue reference термы?
2) Неконсистентность. До этого ни один конструктор у тебя не был помечен explicit, а тут внезапно помечен. Почему мономы и рациональные числа можно неявно конвертировать, а полиномы нельзя?

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/polynomial.h
> +        Polynomial& operator+=(const Polynomial&) noexcept;
А где бинарное сложение?

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/polynomial.h
> +        bool ReduceBy(const std::vector<Polynomial>& F) noexcept;
1) Полином не должен уметь себя редуцировать. Это задача алгоритма.
2) Редукция зависит от порядка, получается он у тебя скрыто везде подразумевается.
3) Плохо зависеть от конкретного контейнера.
4) Еще хорошо бы иметь не inplace версию.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/polynomial.cpp
> +    : monomials_(monomials)
Поздравляю, ты не воспользовался тем, что у тебя rvalue reference. Тут надо писать
```cpp
 : monomials_(std::move(monomials))
```

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/polynomial.cpp
> +        Normalize(monomials_);
Вместо такого подхода лучше делать
```cpp
Polynomial::Polynomial(TMonomials&& monomials)
 : monomials_(normalize(std::move(monomials))) {}
```
И тогда у тебя нет необходимости сначала строить объект в некорректном состоянии и потом его поправлять.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/polynomial.cpp
> +    const Monomial& Polynomial::GetHeadMonomial() const noexcept {
Они у тебя хранятся в отсортированном состоянии?

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/polynomial.cpp
> +    bool Polynomial::IsZero() const noexcept {
Порядок методов в cpp файле должен быть точно такой же как в h файле!

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/polynomial.cpp
> +        for (size_t i = 0; i < monomials.size(); i++) {
Тут тебе не нужен индекс, ты можешь сделать range for

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/polynomial.cpp
> +            monomials[i] = -monomials_[i];
У тебя же был метод *= -1, который эффективнее.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/polynomial.cpp
> +        return Polynomial(std::move(monomials));
Тут можно не писать Polynomial, просто return std::move(monomials);

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/polynomial.h
> +        Polynomial& operator+=(const Polynomial&) noexcept;
Неконсистентность. Ты по разному группируешь операторы в интерфейсах разных классов. Приведи к единому виду.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/polynomial.h
> +        friend Polynomial operator*(Polynomial, const Monomial&) noexcept;
А где умножение полиномов между собой?

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/polynomial.cpp
> +        monomials.shrink_to_fit();
Нахуя, а главное зачем? Это лишь потенциальная реаллокация. Которая может быть лишней, так как у тебя результат операции может быть потом использован для чего-то еще (например для умножения, где понадобится увеличение размера контейнера). Я не вижу смысла в этой операции тут.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/polynomial.cpp
> +    Polynomial operator*(Polynomial left, const Monomial& right) noexcept {
Плохо, что эта операция не симметрична. Ты тогда не можешь слева моном поставить в умножении на многочлен.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/polynomial.cpp
> +    bool Polynomial::ReduceBy(const std::vector<Polynomial>& F) noexcept {
Что означает булев результат? Как понимать когда возовращается true, а когда false? То ли true означает, что он был редуцирован, то ли true означает, что была совершена редукция. Вместо этого заведи enum class ReductionStatus и возвращай конкретный статус операции. Или может быть еще какую структуру с информацией о результате.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/polynomial.cpp
> +                        return true;
У тебя тут 5 вложенных scope. Даже в ядре Linux запрещено иметь более 3. Это требует рефакторинга.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/polynomial.cpp
> +            for (size_t i = 0; i < F.size(); i++) {
Тебе нигде не нужен индекс в этом цикле.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/polynomial.cpp
> +        bool changed = true;
Наличие флага означает ошибку дизайна. Ты скорее всего хотел выделить функцию, которая возвращает флаг и вместо вызова функции поместил сюда ее тело.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/polynomial.cpp
> +            if (monomials[i].GetCoef().GetNumerator() == 0) {
недостаточный интерфейс.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/polynomial.cpp
> +        bool isSorted = true;
Уверен?

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/polynomial.cpp
> +            if (monomials[i].GetCoef().GetNumerator() == 0) {
1) Во-первых, есть std::remove, который делает что надо в одну строчку и не ломает сортировку.
https://en.cppreference.com/w/cpp/algorithm/remove
2) Во-вторых, этого цикла вообще не должно быть просто потому что у тебя должен быть инвариант, что нет мономов с нулевыми коэффициентами в полиноме.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/util/polynomial.h
> +
Где потоковые операторы вывода? Почему для всех классов они есть, а для полиномов внезапно нет?

2024-02-19 10:52 UTC, DimaTrushin commented on lib/algo/buchberger.h
> +        void DoProcess(NUtils::TPolynomials& F);
Что за хрень? Сделай нормальное название. Что ты тут делаешь? Строишь базис гребнера? Ну тогда так и назови.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/algo/buchberger.cpp
> +            }
нарушение уровня абстракции, должно быть
```cpp
std::queue<std::pair<size_t, size_t> > pairs_to_check = get_all_pairs(F.size());
```
Причем это даже не пары, а индексы пар. Так что название так себе.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/algo/buchberger.cpp
> +            while(pairs_to_check.size()) {
while(!pairs_to_check.empty())

2024-02-19 10:52 UTC, DimaTrushin commented on lib/algo/buchberger.cpp
> +                if (!S.ReduceBy(F)) {
Очень загадочное условие тут написано.

2024-02-19 10:52 UTC, DimaTrushin commented on lib/algo/buchberger.cpp
> +                const NUtils::Polynomial& fj = F[pairs_to_check.front().second];
Кстати, проверял эффект от наличия const на производительность?

2024-02-19 10:52 UTC, DimaTrushin commented on lib/algo/buchberger.cpp
> +                const NUtils::Monomial& gi = fi.GetHeadMonomial();
Ты ожидаешь, что в F у тебя все полиномы отсортированы?

2024-02-19 10:52 UTC, DimaTrushin commented on benchmarks/sum/main.cpp
> +uint64_t sum_simple(const std::vector<uint32_t>& a) {
Если ты объявляешь что-либо в cpp файле (пусть то функция, класс, переменная, шаблон) все должно быть внутри anonymous namespace.

2024-02-19 10:52 UTC, DimaTrushin commented on benchmarks/sum/main.cpp
> +        __builtin_prefetch(&a[i + 16]);
Очень плохая тема. Никогда не используй интринзики напрямую. Всегда пользуйся библиотеками вроде vector class library
https://github.com/vectorclass/version2
Потому что не каждый интринзик выполняется на каждом процессоре. Это делает твой код максимально не протируемым. У тебя программа скомпилируется, запустится и упадет лишь во время обращения к интринзику с ошибкой ОТ ПРОЦЕССОРА о том, что такая инструкция не поддерживается. Всегда нужно делать run-time dispatch на уровень поддерживаемых симдов и по указателям на функции подключать нужные методы в зависимости от того, что доступно в run-time. Можешь посмотреть сколько приходится городить для такой поддержки в моем проекте TypingAnalysis
https://github.com/DimaTrushin/TypingAnalysis/tree/kernel

2024-02-19 10:52 UTC, DimaTrushin commented on benchmarks/sum/main.cpp
> +        sum += _mm512_reduce_add_epi32(_mm512_loadu_epi32(&a[i]));
Ну я даже не знаю ни одного процессора на котором это запустится. Спасибо тебе за невозможность запустить твой проект нигде кроме супер современной экзотики.

2024-02-19 10:52 UTC, DimaTrushin commented on benchmarks/buchberger/main.cpp
> +namespace GroebnerBasisLibF4 {
Это все надо в anonymous namespace заворачивать.

2024-02-19 10:52 UTC, DimaTrushin commented on benchmarks/benchmarking.h
> +void Benchmark(TFunction func, double timeout, std::string name, Args... args) noexcept {
Должен быть perfect forwarding. Принимай аргументы через Args&&... А еще лучше так
```cpp
void Benchmark(TFunction&& func, double timeout, const std::string& name, Args&&... args) noexcept {
```

2024-02-19 10:52 UTC, DimaTrushin commented on benchmarks/benchmarking.h
> +        func(args...);
Тут должен быть perfect forwarding
```cpp
(std::forward<TFunction>(func))(std::forward<Args>(args)...);
```

2024-02-19 10:52 UTC, DimaTrushin commented on benchmarks/benchmarking.h
> +        func(args...);
Меня сильно смущает, что эта функция ничего не возвращает.

2024-02-19 10:52 UTC, DimaTrushin commented on benchmarks/benchmarking.h
> +    bool is_good = false;
Убрать все флаги и переделать на нормальные вызовы функций.

2024-02-19 10:52 UTC, DimaTrushin commented on benchmarks/benchmarking.h
> +    const auto start = high_resolution_clock::now();
Блять, у меня в мануале даже написано как надо делать измерение производительности в общем виде.
Посмотри вот тут
https://stackoverflow.com/questions/879408/c-function-wrapper-that-behaves-just-like-the-function-itself
Ответ от Mykola Golubev и комментарии к нему.

2024-02-19 10:52 UTC, DimaTrushin commented on benchmarks/benchmarking.h
> +            if (double(abs(expected - expected_prev)) / double(expected) < 0.01) {
Что за магические константы и сложные условия? Заведи нормальные функции. Сделай класс тестировщик, чтобы все вспомогательные функции и данные лежали в нем.

2024-03-22 10:05 UTC, KaurkerDevourer commented on benchmarks/benchmarking.h
> +    const auto start = high_resolution_clock::now();
Тут скорее правильнее назвать prepare_benchmarking, потому что этот бенчмарк у меня заточен под то, чтобы отработать ровно 10 секунд. Нужно, чтобы пользователь хоть примерно понимал - а если я поставлю в бенчмарке исполниться 1'000'000 раз - сколько мне ждать?

Но в целом я понял, что можно просто сделать запуск 10 раз обычного бенчмарка и и так примерно увидеть, выпилю.

2024-03-22 10:10 UTC, KaurkerDevourer commented on README.md
> +g++ main.cpp -o ../bin/test -O3 -mavx512f -mavx512cd -mavx512er -mavx512pf -mavx512dq -mavx512vl -mavx512ifma -mavx512vbmi -mavx512bw
Виртуальная машина да, но я действительно уберу все это и буду использовать обертки как ты описал ниже и в мануале.

2024-03-22 10:12 UTC, KaurkerDevourer commented on lib/util/math.cpp
> +        int64_t az = __builtin_ctz(a);
Всё правда, пока вообще уберу этот файл, буду юзать std::gcd. Оптимизировать такие не важные штуки, тем более под все процессоры и компиляторы пожалуй буду в конце и вообще вряд ли имеет смысл (вероятно в std самое оптимальное)

2024-03-22 10:13 UTC, KaurkerDevourer commented on lib/util/math.h
> +    int64_t gcd(int64_t a, int64_t b) __attribute__((const));
Такой gcd сильно быстрее (вдвое), атрибут в конце ну, помогает если было вызвано какое-то выражение
gcd(1, 2) + gcd(1,2) - вызовет функцию лишь 1 раз вместо 2.

2024-03-22 10:17 UTC, KaurkerDevourer commented on lib/util/rational.cpp
> +        numerator_ *= other.GetDenominator();
Почему-то считал что Сишные ассерты работают не только в дебаге. Прочитал, вроде только в нем то есть на производительности не скажутся. В любом случае, если это не так, найду only_debug ассерты. Поставил

2024-03-22 10:18 UTC, KaurkerDevourer commented on lib/util/rational.cpp
> +        numerator_ = GetNumerator() * other.GetDenominator() + other.GetNumerator() * GetDenominator();
Тут меня просто смутило, что есть объект такого же класса, и я захотел делать в одном стиле внутри функции, но кажется ты более прав

2024-03-22 10:19 UTC, KaurkerDevourer commented on lib/util/rational.cpp
> +        return (left.numerator_ != right.numerator_) || (left.numerator_ != 0 && (left.denominator_ != right.denominator_));
тоже тут пытался выдрочить перф. Почему-то давно понял, что перф нужно оптимайзить в узких местах (90-10 правило), но не могу смириться. Поправил

2024-03-22 10:22 UTC, KaurkerDevourer commented on lib/util/rational.cpp
> +        return left.numerator_ * right.denominator_ < right.numerator_ * left.denominator_;
А вот тут по-подробнее. Да, это действительно проблема, но как ее решить? Неужто написать нечто CHECK_OVERFLOW и в каждый метод пробрасывать? Это уже напрямую на перф влияет. Или сделать чтобы только в дебаге было?

2024-03-22 10:40 UTC, KaurkerDevourer commented on lib/util/monomial.cpp
> +        for (size_t i = 0; i < std::min(left.term_.size(), right.term_.size()); i++) {
пока не понял почему

2024-03-22 10:41 UTC, KaurkerDevourer commented on lib/util/monomial.cpp
> +        Normalize(term_);
Логично, но в данный момент не уверен что их нет. Делить же можем, теоретически может наделить плохо, посмотрю внимательнее

2024-03-22 10:45 UTC, KaurkerDevourer commented on lib/util/monomial.h
> +        bool IsDivisibleBy(const Monomial&) const noexcept __attribute__((pure));
__attribute__((const)) ведь тоже компиляторы зависимый. В любом случае выпилю, сначала просто напишу разумное без компиляторных зависимостей, потом посмотрю получается ли ускорить на моем конкретном компиляторе, и если получается подумаю можно ли в целом ускорить.

2024-03-22 10:46 UTC, KaurkerDevourer commented on lib/util/polynomial.cpp
> +    const Monomial& Polynomial::GetHeadMonomial() const noexcept {
Да, в этом весь смысл std::vector

2024-03-22 10:52 UTC, KaurkerDevourer commented on lib/util/rational.h
> +    private:
мне казалось так читабельнее

2024-03-27 13:56 UTC, KaurkerDevourer commented on lib/util/polynomial.h
> +        const Monomial& GetHeadMonomial() const noexcept;
почему же? Или ты про Monomial? Получать основной Моном или Терм у полинома необходимо, как предлагаешь иначе?

2024-03-27 13:59 UTC, KaurkerDevourer commented on lib/util/polynomial.cpp
> +        bool isSorted = true;
Да, в этом смысл хранения в векторе

2024-03-27 14:02 UTC, KaurkerDevourer commented on lib/util/polynomial.cpp
> +        bool changed = true;
Вот тут и правда не понял. Почему наличие флага означает ошибку дизайн? У меня флаг - changed, то есть было ли изменение. Если не было изменений, мы выходим. Если были, продолжаем работу

2024-03-27 15:45 UTC, KaurkerDevourer commented on lib/util/polynomial.cpp
> +            if (monomials[i].GetCoef().GetNumerator() == 0) {
Да, так и должно быть, поправлю. Пока на случай багов существует

2024-03-28 09:00 UTC, KaurkerDevourer commented on benchmarks/benchmarking.h
> +#include <chrono>
Эта функция запускает бенчмарки ровно на 10 секунд. Да, они не точны, но на данной стадии проекта хотелось бы такое иметь (f4 в 65 раз быстрее Buchberger). Естественно, в будущем, все реализации будут измерены стандартным бенчмарком с таймером в конструкторе и деструкторе. Сюда не смотри, считай это чисто для меня

2024-04-03 16:56 UTC, KaurkerDevourer commented on lib/util/monomial.h
> +        void AddCoef(const Monomial& other) noexcept;
тут добавляется коэффициент, в том плане что +=

2024-04-06 15:46 UTC, KaurkerDevourer commented on lib/algo/buchberger.cpp
> +                const NUtils::Monomial& gi = fi.GetHeadMonomial();
Нет, ты про то что внутри полинома все мономы отсортированы? Тогда да

2024-04-08 09:13 UTC, KaurkerDevourer commented on benchmarks/benchmarking.h
FakeBenchmark - чисто для меня, потом выпилю. Нормальный бенчмарк написал сюда же

2024-04-09 16:31 UTC, KaurkerDevourer commented on benchmarks/sum/main.cpp
> +#include "../benchmarking.h"
чисто тестовый файлик, удалю чтобы тебя не смущал

2024-04-09 16:40 UTC, KaurkerDevourer commented on tests/rational/main.cpp
> +int main() {
Я не хочу ставить на них блок, если тест вызывает exception то сам же должен их ловить и обрабатывать, иначе падать. Так можно пропустить неизвестные исключения

2024-04-09 16:42 UTC, KaurkerDevourer commented
Комментарии относящиеся к сборке порезолвил - в данный момент основная задача перевести всё на cmake, чтобы не было проблем со сборкой и пофиксить остальные комментарии (остались только важные, которые за бьстро не пофиксить).
После фикса остальных комментариев (в которые включается добавление поля вычетов по модулю, исключение дефектного порядка из мономов), останется только написать сам f4 и бенчмаркать

2024-04-15 10:26 UTC, KaurkerDevourer commented on benchmarks/buchberger.cpp
> +    void FakeTestForRazogrev(gb::PolynomialSet<gb::fields::Rational>& ideal) {
Без этого прям видно, что бенчмарк который запустить первым сильно проседает. Сделал пока что не супер точные бенчи - всего по одному запуску. Правильнее делать много запусков но тут проблема - придется копировать input (иначе 1 раз найдем базис и будем каждый следующий раз просто проверять что это он), а PolynomialSet очень долго копируется, и в итоге бенч еще не точнее. Но это не сложно поправить, просто сделаю для всех библиотек методы которые делают не inplace (И мб еще как-то пошаманю, чтобы каждый следующий расчет хоть сколько-то считался, а не оптимизировался).

2024-04-20 14:06 UTC, KaurkerDevourer commented on lib/util/monomial.cpp
> +        }
Пользователь снаружи и так получает std::vector<uint64_t>, куда удобнее то)

2024-05-03 09:13 UTC, merged

2024-05-05 17:36 UTC, DimaTrushin reviewed
Прошелся по коду. Сделал много разных замечаний. Как обчно, обрати внимание на то, что я не повторялся, если ошибка или проблема встречается несколько раз. Я ожидаю, что ты исправишь по аналогии во всех похожих местах.

2024-05-05 17:36 UTC, DimaTrushin commented on CMakeLists.txt
> +    lib/util/critical_pair.hpp
1) Почему такая неконсистентность в названиях хедеров? У тебя часть файлов .h часть .hpp. Перейди на единый стиль.
2) Не надо добавлять h файлы в add_executable или add_library. Эти диррективы передают файлы компилятору. А компилироваться должны только cpp файлы, h файлы нужны лишь для того, чтобы их инклудить в cpp.

2024-05-05 17:36 UTC, DimaTrushin commented on benchmarks/benchmarking.h
> +using u32 = int32_t;
1) Не делай глобальных юзингов особенно в h файлах. Эти юзинги потом тебе крови попьют, когда ты заинклудишь их куда-нибудь, а у тебя конфликт имен.
2) НИКОГДА НЕ пиши в global namespace. Заведи пространство имен для проекта. Если тебе нужны вспомогательные подпроекты, выдели их в отдельное пространство имен. Старайся типы и их юзинги декларировать внутри классов и в приватной части. Если что-то хочется сделать глобальным, то либо помести это в дополнительное пространство имен, либо делай это хотя бы в cpp файле внутри anonymous namespace.

2024-05-05 17:36 UTC, DimaTrushin commented on benchmarks/benchmarking.h
> +        call(function), text_(text), start_time_(::clock()) {}
раз принимаешь function by value, то делай мув из аргумента call(std:move(function))

2024-05-05 17:36 UTC, DimaTrushin commented on benchmarks/benchmarking.h
> +        call(function), text_(text), start_time_(::clock()) {}
Аналогично, тут может быть полезно принимать std::string by value и так же мувать из аргумента. Я понимаю, что это все мелочи, но это то за что у меня цепляется глаз.

2024-05-05 17:36 UTC, DimaTrushin commented on benchmarks/benchmarking.h
> +    operator TFunction() {
Интересно как это работает. Не увидел у тебя в коде использование этого каста нигде.

2024-05-05 17:36 UTC, DimaTrushin commented on benchmarks/benchmarking.h
> +    TFunction call;
Еще можно сделать приватным аргументом. Тогда можно сделать так
```cpp
template<class R, class... TArgs>
R operator()(TArgs&&... args) const {
  return call(std::forward<TArgs>(args)...);
}
// И потом можно вызывать
test_time(function, "text")(arg1, arg2);
```

2024-05-05 17:36 UTC, DimaTrushin commented on benchmarks/main.cpp
> +int main() {
У тебя не отключены exception, потому надо поставить блок на них. Это делается так
```cpp
#include "Tests.h"
#include "Except.h"

int main() {
  try {
    nn::run_all_tests();
  } catch(...) {
    except::react();
  }
  return 0;
}
Except.h
namespace except {
void react();
}
Except.cpp
#include "Except.h"

namespace except {
void react() {
  try {
    throw;
  } catch(std::exception& e) {
    // обрабатываешь известные исключения
  } catch(...) {
    // обрабатываешь незивестные исключения
  }
}
}
```
И в целом функция main ничего не делает сама. Она всю работу делегирует другим кускам кода. Ее задача -- оркестровка и дать протечь ошибкам в операционку.

2024-05-05 17:36 UTC, DimaTrushin commented on benchmarks/main.cpp
> +    #ifdef NDEBUG
Лучше не добавлять диррективы препроцессора в код. Ты по сути хочешь тут напечатать приветствие. Сделай для этого отдельную функцию, которая проверяет в каком она режиме и печатает приветствие. Ты можешь constexpr переменную определить с помощью проверки NDEBUG и уже потом содержмое этой переменной печатать независимо от режима (ну и можешь выбрать опцию не печатать, если приветствие пустое). Тогда работа с макросами будет вынесена отдельно в кусок кода, который составляет приветствие, а не будет находиться в бизнес логике.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/algo/buchberger.cpp
Старайся не оставлять пустые файлы.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/term.h
> +    class TTerm : public std::vector<uint64_t> {
Очень-очень плохая практика. Прежде чем публично наследоваться от контейнера, ты должен быть уверен в следующем:
1) все методы контейнера имеют смысл для твоего класса в точности с теми именами и сигнатурами с которыми они присутствуют в контейнере.
2) все состояния контейнера корректны и имеют смысл для твоего класса.
3) Независимый вызов любого метода из контейнера не ломает инвариантов твоего класса.

Судя по тому что я вижу, ни одно из этих свойств НЕ выполнено.
1) Например у вектора есть метод size, который не имеет смысла для терма.
2) У тебя не все возможные состояния контейнера доступны, например ты скорее всего обрезаешь в конце переменные с нулевыми степенями в методе Normalize.
3) У вектора есть методы push_back и pop_back, которые ломают твой инвариант (у тебя есть дополнительное данное).

В итоге у тебя НЕ безопасный класс, который может легко себя поставить в некорректное состояние.

Конкретно в этом случае надо делать вектор переменной класса. Во-первых, ты тогда с помощью имени этой переменной сможешь сказать, что ты там хранишь. Так же совсем не понятно в чем смысл базового вектора, что за величины uint64_t там лежат и какой у них смысл.
Я бы сделал так
```cpp
class TTerm {
using Index = uint64_t;
using Degree = uint64_t;
public:
  Degree degree(Index i) const {
    if (i >= variables_.size())
      return 0;
    return variables_[i];
  }
private:
  std::vector<Degree> variables_;
  Degree total_;
};
```
Вот что-то типо такого.

Бывают ситуации, когда нужно наследоваться от контейнера, но в этом случае обычно наследование защищенное или приватное и обязательно одно из условий: а) либо ты используешь protected метод контейнера, б) либо ты раскрываешь какой-то метод контейнера через using директиву. Если ни один из пунктов не выполнен, то это должна быть переменная класса, а не базовый класс.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/term.h
> +            using size_type = typename TBase::size_type;
Вот это вообще не понятно что такое в терминах терма. У тебя есть две величины -- имена индексов у переменной и степени переменных. Вот у тебя потому имеет смысл два типа Index и Degree. А что такое size_type, это хрен его знает. Кроме того, у тебя это имя всегда доступно в векторе. На сколько я помню, нет необходимости делать явный using, раз ты унаследовался публично.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/term.h
> +            using TBase = std::vector<uint64_t>;
Сырой тип using64_t ничего не говорит о том, для чего он нужен. Если я правильно понимаю, ты тут хранишь степени переменных у переменной x_i степень хранится в i-ом элементе вектора. Тогда заведи using Degree = uint64_t. Так мне НЕ надо будет лазить по коду и проверять свою догадку. А так я не могу даже из заголовка класса понять смысл данных которые в нем хранятся.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/term.h
> +            void Normalize();
Перемести приватные методы после публичных. Старайся не тасовать публичные и приватные секции.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/term.h
> +        private:
Лишнее слово private

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/term.h
> +            inline TTerm(size_type sz) : TBase(sz) {}
У этого конструктора нет смысла. Он создает тебе класс терма в некорректном состоянии, в котором не выполнен инвариант, что последний элемент в векторе не нулевой. И если ты это условие где-то используешь, то у тебя большие проблемы.
Кроме того, плохо делать такие конструкторы НЕ explicit, потому что ты можешь легко написать TTerm t = 5; все скомпилируется и хер пойми, что это значит.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/term.h
> +                }
есть же std::accumulate.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/term.h
> +            inline TTerm() : TBase() {}
Это пишется не так
```cpp
TTerm() = default;
```

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/term.h
> +            inline TTerm(std::initializer_list<uint64_t> il) : TBase(il) {
Почему этот метод НЕ вынесен в cpp файл.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/term.cpp
> +    void TTerm::Normalize() {
Порядок методов в cpp файле должен быть точно такой же как в h файле!

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/term.h
> +
Я бы добавил операторы сравнения на равенство и неравенство == и !=. Это имеет смысл для термов.
Еще может пригодиться спросить у терма равен ли он 1. Надо только придумать как этот метод назвать.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/term.cpp
> +        return left;
Проверь выполняется ли тут мув из аргумента или копирование. Я просто не помню, надо ли тут std::move добавлять. Просто NRVO тут НЕ тригерится из-за того что это не локальная переменная, а аргумент функции. А вот копия или мув я не могу вспомнить. Каждый раз приходится проверять.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/term.cpp
> +            }
Вот тут есть общий код, ты всегда выводишь out << "x_" << i;
И потом уже под if-ом надо ли выводить степень или нет. Но это мелочи. Можно и так и так.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/term.cpp
> +            sum_ += other[i];
Почему не сделать проще вне цикла написать sum_ += other.sum_;?

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/term.cpp
> +        if (other.size() > size()) {
Это чушь. Эта ситуация это assert. Программист НЕ проверил на то, что текущий терм НЕ делится на other.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/term.cpp
> +            (*this)[i] -= other[i];
Как минимум проставь assert-ы на underflow, чтобы если программист забыл проверить, что один моном на другой не делится у тебя это отловилось в дебаге.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/term.cpp
> +            sum_ -= other[i];
sum_ -= other.sum_; вне цикла.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/term.cpp
> +    uint64_t TTerm::GetDegree() const noexcept {
можно просто назвать totalDegree

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/term.cpp
> +        return std::move(term);
Вот тут лишний std::move. Причем он ухудшает производительность. У тебя term является локальной переменной метода, а значит для нее возможно nrvo. Вместо этого ты делаешь каст, которые вместо nrvo тригерит обычный move. Чтобы затригерилось nrvo надо чтобы тип возвращаемого выражения был один в один таким же, как указанный в сигнатуре функции тип. У тебя тип возвращаемый функцией TTerm, а тип выражение TTerm&&. Потому nrvo НЕ случилось.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/term.cpp
> +        for (size_t i = 0; i < other.size(); i++) {
тут приходит на ум std::any_of

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/rational.h
> +    using denominator = int64_t;
Эти типы имет смысл только внутри Rational. Зачем они тут снаружи доступные глобально? Еще, называй типы так, чтобы отличать их от переменных. Например начинай их имена с большой буквы, это просто выполнимо и очень улучшит читаемость конструкторов. Кроме того, нет смысла иметь разные типы для числителя и знаменателя. У тебя есть тип для целого числа, который ты хочешь использовать для рациональных чисел, а не тип числителя и тип знаменателя. Это лиш ухудшает читаемость кода.

Сделай один приватный тип using Integer = int64_t; или что-то в этом духе.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/rational.h
> +        bool MoreThanZero() const noexcept ;
Лишний пробел между noexcept и ;. Настрой ide так, чтобы clang-format применялся на сохранение файла. Тогда тебе не придется руками мучиться с форматированием.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/rational.h
> +        Rational(numerator numerator = 0, denominator denominator = 1);
Присвой эти же дефолтные значения внизу самим переменным при объявлении.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/rational.cpp
> +        int64_t gcd = std::gcd(abs(numerator_), abs(denominator_));
1) std::gcd и так по умолчанию считает gcd от модулей величин. Потому не надо добавлять лишний abs.
2) Вот эта строчка хорошо показывает, что у тебя нет смысла иметь разный тип для числителя и знаменателя. Ты теперь не знаешь как назвать тип для gcd. Он не тип числителя и не тип знаменателя, но тем не менее, он должен быть. Потому ты переходишь на сырые типы, что равносильно магической константе но на уровне типов. Если ты где-то сменишь тип для числителя и знаменателя на другой, то тут у тебя будет битая зависимость типа.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/rational.cpp
> +    Rational pow(const Rational& number, int64_t power) noexcept {
Есть подозрение, что с такой имплементацией из кучи разных return statemet-ов у тебя вообще не тригерится nrvo и у тебя на каждый вызов еще дополнительно уходит память на стеке под ответ каждой функции в рекурсивном вызове. Если же сделать одну переменную и сделать ее рекурсивное обновление, а потом ее вернуть, то у тебя все функции в рекурсии будут хотя бы работать in place. Ну и в приличном обществе эту функцию пишут циклом.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/rational.cpp
> +        return left.numerator_ * right.denominator_ <= right.numerator_ * left.denominator_;
Не дублируй имплементацию. Что мешало написать
```cpp
return !(right < left);
```
??

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/rational.h
> +        bool MoreThanZero() const noexcept ;
Функции, которые возвращают bool должны иметь в начале глагол вроде is или has или что-то в этом духе. Этот метод называется isPositive() const;

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/rational.cpp
> +        //assert(other != 0);
почему убрал assert?

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/rational.cpp
> +        numerator_ *= other.GetDenominator();
assert-ы включены по умолчанию. Но они отключаются, если объявлен макрос NDEBUG. По умолчанию msvc определяет этот макрос в release, а gcc и clang нет и потому для них надо отдельно в релизе этот макрос объявлять. Это специально сделано, чтобы ловить свои ошибки и уметь быстро отключать проверки, чтобы не надо было лазить по коду и комментировать/раскомментировать код. Вообще можно сделать еще и свои кастомные ассерты, чтобы можно было разными макросами разные проверки отключать. Ну и конечно же нужно уметь включать assert-ы в релизе (это та причина почему gcc и clang их по умолчанию не отключают). Это связано с тем, что какие-то ошибки могут посыпаться только в релизе из-за наличия UB или/и оптимизаций от компилятора.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/rational.cpp
> +        numerator_ *= other.GetNumerator();
Если уж совсем заморачиваться, то тут надо заморачиваться над переполнением. Для этого можно найти gcd для numerator_ и other.denominator_ и поделить на него их обоих. И потом аналогично для denominator_ и other.numerator_ и только после этого перемножать. И тогда еще и не придется делать Normalize.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/rational.cpp
> +        numerator_ = numerator_ * other.GetDenominator() + other.GetNumerator() * denominator_;
Тут можно заморочиться через lcm для общего знаменателя, чтобы позже наступало переполнение. Но не знаю на сколько это скажется на производительности.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/rational.h
> +        friend bool operator!=(const Rational&, const Rational&) noexcept;
Сгруппируй все операторы сравнения вместе, и не раскидывай их по коду. Туда же можешь добавить методы из разряда isPositive, isNegative, isZero, isOne и так далее.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/rational.cpp
> +        return left.numerator_ == right.numerator_ && (left.numerator_ == 0 || left.denominator_ == right.denominator_);
По хорошему у тебя должен быть инвариант, что если numerator_ == 0, то тогда denominator_ == 1. Потому а) дополнительная проверка на равенство нулю лишняя. б) Надо этот инвариант проверять.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/prime_field.hpp
> +        for (uint32_t i = 2; i * i <= n; i++) {
Вынеси проверку на 2 до цикла, а потом сделай цикл
```cpp
for (uint32_t i = 3; i * i <= n; i+=2)
```
Это ускорит проверку в 2 раза.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/prime_field.hpp
> +            uint64_t half = binpow(value, pow/2, mod);
пробелы по краям оператора деления /.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/prime_field.hpp
> +            return (value * binpow(value, pow - 1, mod)) % mod;
А вот не было бы рекурсии, то мог бы сделать constexpr функцию.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/prime_field.hpp
> +    uint64_t binpow(uint64_t value, int32_t pow, int32_t mod) {
У тебя в этой функции mod является занковым числом int32_t, а в классе ниже параметр является беззнаковым uint32_t. Потому если ты используешь эту функцию в классе ниже, то у тебя есть потенциально некорректные вызовы этого метода. Зачем так делать я НЕ знаю.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/prime_field.hpp
> +        static const uint32_t mod = Mod;
Убери это говно.
1) Во-первых, никогда НЕ пиши никакой код после переменных класса. Переменные класса в таком дизайне как у тебя (кода в начале публичная часть класса), должны быть в самом конце класса, иначе как их вообще найти?
2) Во-вторых, НЕ надо переводить compile-time данные в run-time данные. Если тебе не нравится имя Mod, то сделай его mod и используй его. Шаблонный параметр класса всегда из него доступен и не требует его дополнительного хранения.
3) В-третьих, такая байда потенциально снижает производительность. Потому что ты теперь работаешь с переменной, которая имеет адрес в памяти, а не просто константа компиляции.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/prime_field.hpp
> +        uint64_t number_;
Если у тебя mod является числом типа uint32_t, то НЕТ смысла хранить uint64_t. Я знаю зачем ты его используешь. Чтобы не было переполнения при умножении. Ну так и используй uint64_t только при умножении, то есть ты сначала кастанешь uint32_t к uint64_t и потом перемножишь и потом возьмешь остаток и потом положишь его в uint64_t. Хранить же лишние 4 байта нулей нет смысла. Ты так будешь лучше в кеш попадать.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/prime_field.hpp
> +    uint64_t binpow(uint64_t value, int32_t pow, int32_t mod) {
Почему у Rational этот метод был френдом объявленным внутри класса и имел имя pow, а тут этот метод объявлен вне класса, имеет другое название и имеет типы аргументов НЕ согласованные с типами данных из класса?

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/prime_field.hpp
> +    uint64_t binpow(uint64_t value, int32_t pow, int32_t mod) {
Не консистентные названия методов. У тебя то с большой то с маленькой буквы начинаются имена методов. То у тебя они в CamelCase, то вот так слитно сокращением.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/prime_field.hpp
> +        PrimeField(int64_t number = 0)
перенеси этот дефолтное значение в место объявления остатка. А тут добавь дефолтный конструктор.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/prime_field.hpp
> +                number += Mod;
У тебя number является int64_t, а Mod -- uint32_t. Такого прибавления может быть не достаточно для изменения знака. Надо сначала сделать number %= Mod и потом если он отрицательный, то сделать += Mod.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/prime_field.hpp
> +            static_assert(IsPrime(Mod));
бедный компилятор =)
Если уж ты такие проверки делаешь, то делай run-time проверки на корректность всех аргументов всех методов. Например для деления на 0.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/prime_field.hpp
> +            *this *= binpow(other.number_, Mod - 2, Mod);
нужен assert на деление на ноль.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/comp.hpp
> +#include "critical_pair.hpp"
Какого хрена у тебя порядки зависят от критических пар? Убрать.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/comp.hpp
> +        bool operator()(const Monomial<T>& left, const Monomial<T>& right) const noexcept {
Я так понимаю ты перепишешь на зависимость от термов, а не от мономов, потому я оставляю это без комментариев.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/critical_pair.hpp
> +            const TPolynomials<TCoef>* F_;
Если хочешь гарантировать, что эта штука никогда не nullptr, то можно сделать std::reference_wrapper<const TPolynomial<TCoef>> F_; Тогда эта штука будет как полином себя вести и не надо будет всякие звездочки рисовать и будет гарантия от компилятора, что это не nullptr.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/critical_pair.hpp
> +            uint64_t degree_;
У тебя у монома уже есть свой тип для степени. Раз у тебя есть классы, которые используют типы имеющиеся в других классах, то надо сделать публичный using Degree = uint64_t; в мономе, а потом тут в начале сделать публичный 
```cpp
private:
using Monomial = Monoial<TCoef>;
public:
using Degree = typename Monomial::Degree;
```

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/critical_pair.hpp
> +            const TPolynomials<TCoef>* F_;
Не таскай тип для полинома с параметром, заведи using Polynomial = TPolynomial<TCoef>;
И еще не используй множественное число для названия класса многочленов. Это неудобно.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/critical_pair.hpp
> +            CriticalPair() = default;
Если есть дефолтный конструктор, то для каждого поля укажи дефолтное значение. Или вообще убери дефолтный конструктор, если он НЕ имеет смысла. А по мне он как раз не должен иметь смысл.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/critical_pair.hpp
> +            CriticalPair(const TPolynomials<TCoef>* F, size_t i, size_t j)
Лучше принимать многочлен по константной ссылке, а не по указателю. Иначе у пользователя будет ощущение, что многочлен может измениться.
И еще вообще не понятно, что такое i и j. Это номера мономов в многочлене?
Я осознал, у тебя TPolynomials это КОНТЕЙНЕР многочленов. Лучше дать имя, которое легче отличить от просто многочлена.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/term.h
> +    class TTerm : public std::vector<uint64_t> {
Зачм у тебя в названии терма в начале есть буква T в начале? У тебя в мономе и многочлене например нет такой буквы. Я обычно использую T только в начале шаблонных параметров, которые являются типами, чтобы в коде легко отличать их от просто классов, потому что шалонные параметры для класса -- это глобальные данные. А у тебя похоже эта буква случайно используется. Надо исправлять.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/critical_pair.hpp
> +                return (*F_)[left_idx_].GetHeadMonomial().GetTerm();
почему ты не пишешь GetLeft().GetHeadMonomial().GetTerm()? Вроде как это сокращает длину текста. Может быть даже стоит добавить функцию GetLeftHeadMonomial и GetLeftHeadTerm. И может быть стоит избавиться от всех слов get для читаемости.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/monomial.hpp
> +        Monomial(const TTerm& term, TCoef coef)
А поему тут нет дефолтного значения для коэффициента?

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/monomial.hpp
> +        , coef_(coef)
добавь std::move(coef), раз принимаешь коэффициент by value. Это не должно повлиять ни на что  твоем случае, но может повлиять в случае тяжелых коэффициентов.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/monomial.hpp
> +            return Monomial(std::move(tmpTerm), -coef_);
Тут можно написать одну строчку return Monomial(term_, -coef_); Зачем что-то еще городить?

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/monomial.hpp
> +        {
Лучше добавь инвариант, если коэффициент 0, то терм равен 1. Сделай так же функцию Normalize, которая все это делает.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/monomial.hpp
> +        int64_t GetNumerator() const noexcept {
Это что за хуйня? С какого перепуга у монома должна быть функция для взятия числителя и знаменателя, если у тебя тип коэффициентов любой и там может не быть смысла в этом методе? Кроме того, ты возвращаешь конкретный тип числителя и знаменателя, а он может отличаться от этого. Я бы рекомендовал убрать это говно отсюда.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/monomial.hpp
> +        Monomial& operator*=(const Monomial& other) noexcept {
Добавь инвариант, что если коэффициент 0, То терм 1. И тут тогда надо будет дополнительно обработать случай нулевого коэффициента у одного из множителей. Я в целом бы рекомендовал этот инвариант имплементировать, потому что у тебя не будут раздуваться термы.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/monomial.hpp
> +            assert(other.GetCoef() != 0);
Этого ассерта мало, надо еще проверить, что соответствующий терм делится.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/polynomial.hpp
> +    class LexComp;
Нахрена это форвард декларейшн тут?

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/polynomial.hpp
> +            #endif
Избегай использования дирректив препроцессора в бизнес логике. Это пишется не так. Сделай метод isPolynomialCorrect, который возвращает bool и вызывай его внутри ассерта assert(isPolynomialCorrect()). Причем ты можешь этот метод сделать приватным методом класса и тогда не надо будет раскать кучу параметров как run-time, так и compile-time.
Правда таким методом придется помучиться с выводом параметров ошибки, которые ты хочешь печатать.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/polynomial.hpp
> +        , isRemoved_(false)
Это что еще за неинтерпретируемая хрень? У меня к ней несколько вопросов. Во-первых, когда у тебя переменная начинается с глагола is, это всегда ошибка дизайна. Ты скорее всего хочешь иметь не булев флаг, а некий статус. И потому тебе нужно enum class PolynomialStatus {Removed, Presented, Curved, Build, Cooked}; и что-то в этом духе. Как минимум тип этой хуйни хоть что-то скажет о том, что это за статус. А имя тогда можено дать более разумное. Потому что тут совсем не понятно, что именно у тебя тут removed.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/polynomial.hpp
> +    template <typename TCoef, typename TComp = LexComp>
Если ты хочешь использовать тип как дефолтный параметр, то тебе не достаточно иметь только forward declaration. Это incomplete type, у тебя компилятор должен ругнуться. Либо ты должен руками подключать компараторы, а это зависимые хедеры, что ни в коем случае не рекомендуется делать. Это превращает твой код в хрупкий на уровне сборки. А с этим говном лучше не играть.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/polynomial.hpp
> +        Polynomial(TMonomials<TCoef>&& monomials)
Конструкторы которые так сильно зависят от имплементации лучше делать приватными и звать их только там, где надо. Потому что так пользователю надо знать контейнер в котором хранятся твои мономы внутри полиномов и потом надо еще создать этот контейнер и потом мувнуть его внутрь полинома.

Кроме того, у тебя тип TMonomials НЕ живет внутри Polynomial. Помести соответствующий using внутри, а не цитируй глобальный тип.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/polynomial.hpp
> +    using TMonomials = std::vector<Monomial<TCoef>>;
Убрать, это деталь имплементации многочлена. Спрятать внутри него.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/polynomial.hpp
> +        {
Раз ты принимаешь любой контейнер, который не обязательно посорчен, то у тебя есть два выбора:
1) Ты делаешь его приватным и только методы, которые гарантированно создают отсортированные вектора мономов используют этот конструктор.
2) Ты делаешь его публичным, но тогда добавляешь стадию сортировки (метод  Normalize, привет тебе еще раз), иначе ты разрешаешь создать многочлен в НЕ корректном состоянии.

Выбери один из этих подходов. Мне кажется, что можно обавить оба подхода.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/polynomial.hpp
> +            isRemoved_ = true;
Что это за хрень? Если это требуется для алгоритма, то это дополнительная информация к полиному и надо ее хранить рядом с полиномом, а не внутри полинома. Ты же вводишь критические пары с кучей доп информации. Почему тут у тебя в многочлен какая-то дрянь просочилась?

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/polynomial.hpp
> +                monomials[i] = -monomials_[i];
у тебя же есть более дешовый inplace метод *= -1; Почему не используешь его? Или метод умножения на коэффициент?

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/polynomial.hpp
> +            return Polynomial(std::move(monomials));
Я подозреваю, что этот конструктор тебе нужен только внутри класса. Потому его надо сделать приватным.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/polynomial.hpp
> +            return true;
Это называется
```cpp
return leftMonomials == rightMonomials;
```
Причем не знаю делает ли вектор оптимизацию через размер, потому ее может быть и можно оставить, но стоит проверить есть ли разница.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/polynomial.hpp
> +            for (size_t i = 0; i < monomials_.size(); i++) {
Это не безопасный метод. Надо проверить, что monomial не равен нулю! Иначе у тебя будет длинный вектор из одинаковых нулевых мономов.
Если не хочешь делать такую проверку ради скорости, то сделай приватный метод, который не делает этой проверки и тут сделай проверку и позови приватный метод. А потом везде, где ты можешь гарантировать, что моном не ноль, просто зови метод без проверки.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/polynomial.hpp
> +                Polynomial tmpMonomials = (*this);
убери скобки вокруг *this. Они тут не нужны.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/polynomial.hpp
> +                Polynomial tmpMonomials = (*this);
плохое нзвание для переменной.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/polynomial.hpp
> +            *this = std::move(newPolynomial);
Когда у тебя метод по сути не inplace, то имеет смысл имплементировать метод бинарный operator*, а потом этот имплементировать через него.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/polynomial.hpp
> +        bool isRemoved_ = false;
Судя по всему This flag must be removed.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/util/polynomial.hpp
> +    std::queue<std::pair<size_t, size_t>> GetPairsToCheck(size_t sz) {
Это какой-то метод явно спецфичный для алгоритма отбора пар (то есть для бухбергера и прочих алгоритмов по построению базиса гребнера). Потому ему не место тут.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/algo/buchberger.h
> +        using namespace NUtils;
Это полностью лишает смысла пространство имен NUtils. Потому что ты делаешь using прям в хедере. Потому любой, кто подключит этот хедер будет считать, как будто этого пространства имен нет. Это избавит тебя от ошибок линковки, но не от оверлапа имен во время компиляции. НЕ делай так. Сделай этот using внутри метода по поиску базиса гребнера, не нарушай инкапсюляцию данных.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/algo/buchberger.h
> +                    }
вот это отельный метод по добавлению новых пар.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/algo/buchberger.h
> +                if (!NUtil::ReduceToZero(S, F)) {
И какого хрена ты тут ипользуешь квалификатор пространства имен, когда ты только что раскрыл это пространство имен???

2024-05-05 17:36 UTC, DimaTrushin commented on lib/algo/buchberger.h
> +                const Polynomial<TCoef>& fi = F[pairs_to_check.front().first];
Вот эти две точки подряд говорят, что все тело цикла зависит только от pairs_to_check.fron(). А потому тут должен быть вызван метод, который только от него зависит. И потом ты попаешь из очереди первый элемент.
Кроме того, у тебя стиль имени переменной не соответствует общему стилю.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/algo/buchberger.h
> +                Polynomial<TCoef> S = fi * (glcm/gi) - fj * (glcm/gj);
пробелы вокруг операторов деления.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/algo/buchberger.h
> +                Polynomial<TCoef> S = fi * (glcm/gi) - fj * (glcm/gj);
Думаю это все можно выделить в отдельную функцию подсчета S-полинома. Это сделает код еще более читаемым и не надо будет руками этот полином строить тут.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/algo/buchberger.h
> +                if (!NUtil::ReduceToZero(S, F)) {
А этот метод у тебя inplace действует? Если так, то передавай S  по указателю, а то это совершенно не понятно. Либо еще лучше, возвращай новый полином, запоминай остаток, сравнивай его с нулем и потом уже добавляй его в множество. У тебя тут теряется логика за этим хаком, когда содержательная работа делается внутри if.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/algo/util/groebner_basis_util.h
> +        bool ReduceToZero(Polynomial<TCoef>& F, TPolynomials<TCoef>& polynomialsSet) {
Название метода нагло врет, а точнее даже запутывает. То есть ты говоришь, вот тебе многочлен и множество и отредуцируй мне многочлен F к нулю относительно множества. Но это не всегда можно сделать. Вместо этого ты делаешь другое, совсем НЕ то, что написано в названии функции. Ты говоришь: проверь, редуцируется ли к нулю этот многочлен. И если да, то верни true. Но это две разные функции. Первая -- редуцируй многочлен. Вторая -- проверь результат равен нулю или нет. Разбей это на два таких метода, а этот просто убери!

2024-05-05 17:36 UTC, DimaTrushin commented on lib/algo/util/groebner_basis_util.h
> +            bool changed = true;
Всегда когда есть флаг, это ошибка дизайна. Ты на самом деле смешал два метода в один и потому у тебя тут такой безобразный код. Но первая часть этого кода делает следующее: Ты хочешь редуцировать, пока редуцируется. То есть у тебя технически код выглядит так
```cpp
size_t reductions = tryReduceOnce(F, Set);
while (reducetions != 0) {
  reductions = tryReduceOnce(F, Set);
}
```
И вот уже метод tryReduceOnce внутри проходит по всему Set и редуцирует каждый многочлен F относительно текущего пока может. И там тоже будет два метода tryReduceOnce и так далее.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/algo/util/groebner_basis_util.h
> +                    while (!F.IsZero() && F.GetHeadMonomial().GetTerm().IsDivisibleBy(f.GetHeadMonomial().GetTerm())) {
Я так понимаю, ты тут делаешь ускрение проверки редукции тем, что редуцируешь только старший моном. Ну тогда сделай метод reduceHead или что-то такое и делай его.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/algo/buchberger_with_criterias.h
> +        bool ReduceToZero(Polynomial<TCoef>& F, TPolynomials<TCoef>& polynomialsSet) {
У тебя же уже есть методe ReduceToZero. Зачем тут еще один? Если они чем-то отличаются и это важно, то надо их разделить хотя бы пространством имен или названием. Если один и тот же, то надо убрать дуплицирование кода.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/algo/buchberger_with_criterias.h
> +        TPairsQueue GetPairsToCheckWithCriterias(const TPolynomials<TCoef>& polynomials) {
убери s на конце. Гугли верное написание слов на английском.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/algo/buchberger_with_criterias.h
> +                    }
Судя по всему у тебя обычный бухбергер от этого отличается лишь в этом месте. И потому тут можно просто вызывать функцию отвечающую за апдейт пар и подменять одну на другую и получатся разные алгоритмы и не надо будет код переписыватьпо 10 раз.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/algo/buchberger_with_criterias_version2.h
> +                if (fi.IsRemoved() || fj.IsRemoved()) {
Судя по всему тебе надо хранить не сами многочлены, а новую информацию, которая состоит из многочлена и его статуса. Убери этот статус из многочлена!

2024-05-05 17:36 UTC, DimaTrushin commented on lib/algo/buchberger_with_criterias_version2.h
> +            }
есть же std::remove!

2024-05-05 17:36 UTC, DimaTrushin commented on lib/algo/f4.h
> +        using TPairsSet = std::set<CriticalPair<TCoef>, DexComp>;
А почему именно set, а не vector?

2024-05-05 17:36 UTC, DimaTrushin commented on lib/algo/f4.h
> +                L.push_back(pair.GetGlcmTerm() / pair.GetLeftTerm() * pair.GetLeft()); // add left
зачем тут комментарий. Если не понятно, что делает код, то заведи функцию с нужным имененем и вызови ее тут.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/algo/f4.h
> +        using namespace NUtils;
убрать

2024-05-05 17:36 UTC, DimaTrushin commented on lib/algo/f4.h
> +                    }
вот это опять бы выделить в отдельную функцию.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/algo/util/matrix_reduction.h
> +        using TDiffSet = std::set<TTerm, TTermReverseComp>;
Плохое название типа, оно должно отражать не имя переменной, а именно класс объектов, которому принадлежит переменная этого типа. То есть это TermSet как минимум.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/algo/util/matrix_reduction.h
> +            TCoef matrix[F.size()][diffSet.size()];
Ебаное говно, это что динамический массив массивов из сраного си? Ты на каком языке пишешь мать твою? Убрать это говно. Сделай нормальный класс матриц, который внутри аллоцирует один вектор и сделай для нормальный оператор() по паре индексов operator()(int rows, int cols) const. Не используй сишные массивы никогда и ни при каких условиях, это недо объекты, чье появление в языке -- ошибка дизайна.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/algo/util/matrix_reduction.h
> +            std::set<TTerm> leadingTerms;
Не заводи переменные заранее. Старайся объявлять их как можно ближе к использованию и по возможности инициализировать при объявлении.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/algo/util/matrix_reduction.h
> +            for (size_t j = 0; j < diffSet.size(); j++) {
Выдели отдельно гаусса.

2024-05-05 17:36 UTC, DimaTrushin commented on lib/algo/util/matrix_reduction.h
> +            TPolynomials<TCoef> reduced;
Что делает часть кода ниже?

2024-05-05 17:36 UTC, DimaTrushin commented on lib/algo/util/matrix_reduction.h
> +        TPolynomials<TCoef> MatrixReduction(NUtil::TSymbolicPreprocessingResult<TCoef>& L) {
Очень длинная функция требующая рефакторинга и выделения содержательных подшагов в ней.

2024-05-05 17:36 UTC, DimaTrushin commented on tests/testing.h
> +#define ASSERT_EQUAL(A, B) \
Плохо написанный assert. Он у тебя всегда делает проверку, но только при отсутствии макроса NDEBUG падает. Лучше делать так, чтобы твои ассерты полностью вырезались, и не оставляли артефактов. Либо чтобы они никогда не вырезались и падали всегда. В текущей версии вообще не понятно зачем тебе макросы, это всего лишь обычная функция. И нахрена ее через assert тогда имплементировать. И даже если ее имплементировать через assert, то какого хрена она не функция, а макрос. Если сделать функцию и разбить на хедер и cpp, то можно вообще сделать так, чтобы независимо от NDEBUG у тебя сообщалось об ошибке и еще содержательное сообщение посылать.

2024-05-05 17:36 UTC, DimaTrushin commented on benchmarks/groebner_basis.cpp
> +        #ifdef NDEBUG
Вместо этого сделай так, чтобы количество итераций определялось в звисимости от параметра NDEBUG.

2024-05-05 17:36 UTC, DimaTrushin commented on benchmarks/groebner_basis.cpp
> +void benchmark_katsura4() {
Тебе нужны генераторы тестов из каждого семейства.

2024-05-05 18:17 UTC, KaurkerDevourer commented on lib/algo/util/matrix_reduction.h
> +            TPolynomials<TCoef> reduced;
Получает значения из матрицы. Мы же что-то отредуцировали - нужно понять что за полиномы получились

2024-05-06 10:05 UTC, KaurkerDevourer commented on lib/util/monomial.hpp
> +        Monomial& operator*=(const Monomial& other) noexcept {
Нельзя. Ну, то есть можно, но я очень не хочу. При таком инварианте ломается вся сортировка термов, и не очень ясно что делать если 
x^2 - x^2 + x^2. В промежутке терм превратится в 1, а потом?

2024-05-06 11:13 UTC, KaurkerDevourer commented on lib/util/polynomial.hpp
> +            return true;
libcxx делает, но мало ли кто чем компилит, оставлю проверку

2024-05-06 11:20 UTC, KaurkerDevourer commented on lib/algo/f4.h
> +        using TPairsSet = std::set<CriticalPair<TCoef>, DexComp>;
Потому что нужно уметь брать из начала, добавлять куда-то и удалять откуда-то.

2024-05-06 22:44 UTC, KaurkerDevourer commented on lib/util/term.cpp
> +        for (size_t i = 0; i < other.size(); i++) {
Не, тут же сравниваются построчно. Но нечто подобное думаю есть.

2024-05-06 23:29 UTC, KaurkerDevourer commented on CMakeLists.txt
> +    lib/util/critical_pair.hpp
hpp все убрал и пустые cpp файлы тоже, а вот .h не могу не передавать если есть cpp, не работает почему-то. Пока что забью, потом надеюсь дойдут руки разобраться (имхо пофиг же вообще)

2024-05-06 23:30 UTC, KaurkerDevourer commented on CMakeLists.txt
> +    lib/util/critical_pair.hpp
А, лол, сработало =). Хз что поменял

2024-05-07 00:12 UTC, KaurkerDevourer commented on lib/util/monomial.hpp
> +        {
не хочется, ниже написал. x^2 - x^2 + x^2 - что-то плохое случится. Коэффициент 0 у монома вполне корректный, просто с ним надо аккуратно (а я аккуратно)

2024-05-07 00:14 UTC, KaurkerDevourer commented on lib/util/prime_field.hpp
> +            static_assert(IsPrime(Mod));
Тут это важно с точки зрения компиляции. Потому что PrimeField если Mod не prime не должно даже компилиться.

2024-05-07 00:15 UTC, KaurkerDevourer commented on lib/util/rational.cpp
> +        return left.numerator_ == right.numerator_ && (left.numerator_ == 0 || left.denominator_ == right.denominator_);
Тоже не хочется
1/2 - 1/2 + 1/2.
Но тут еще адекватное поведение будет, поэтому мб сделаю